import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

export type QuotePdfInput = {
  tenantName: string;
  quoteNumber: string;
  currency: string;
  customerName: string;
  notes?: string | null;
  lines: Array<{
    description: string;
    quantity: number;
    unitCents: number;
    totalCents: number;
  }>;
  subtotalCents: number;
  taxCents: number;
  totalCents: number;
};

function money(cents: number, currency: string) {
  return `${(cents / 100).toFixed(2)} ${currency}`;
}

/** Portable HTML quote — opens in any browser; no native PDF binary required. */
export function renderQuoteHtml(input: QuotePdfInput): string {
  const rows = input.lines
    .map(
      (l) =>
        `<tr><td>${escapeHtml(l.description)}</td><td>${l.quantity}</td><td>${money(l.unitCents, input.currency)}</td><td>${money(l.totalCents, input.currency)}</td></tr>`,
    )
    .join("");

  return `<!doctype html>
<html><head><meta charset="utf-8"/><title>${escapeHtml(input.quoteNumber)}</title>
<style>
  body{font-family:Segoe UI,Helvetica,Arial,sans-serif;max-width:720px;margin:40px auto;color:#111}
  h1{margin:0 0 4px} .muted{color:#666}
  table{width:100%;border-collapse:collapse;margin-top:24px}
  th,td{border-bottom:1px solid #ddd;padding:8px;text-align:left}
  .totals{margin-top:16px;text-align:right}
</style></head><body>
  <h1>${escapeHtml(input.tenantName)}</h1>
  <p class="muted">Quote ${escapeHtml(input.quoteNumber)}</p>
  <p>Customer: ${escapeHtml(input.customerName)}</p>
  ${input.notes ? `<p>${escapeHtml(input.notes)}</p>` : ""}
  <table><thead><tr><th>Item</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead>
  <tbody>${rows}</tbody></table>
  <div class="totals">
    <div>Subtotal: ${money(input.subtotalCents, input.currency)}</div>
    <div>Tax: ${money(input.taxCents, input.currency)}</div>
    <div><strong>Total: ${money(input.totalCents, input.currency)}</strong></div>
  </div>
  <p class="muted">Generated by AutoQuoteAI</p>
</body></html>`;
}

function escapeHtml(s: string) {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

export async function writeQuoteDocument(
  input: QuotePdfInput,
  objectKey: string,
): Promise<{ absolutePath: string; objectKey: string }> {
  const root = process.env.LOCAL_STORAGE_DIR ?? join(process.cwd(), "../../storage");
  const abs = join(root, objectKey);
  const dir = abs.replace(/[/\\][^/\\]+$/, "");
  await mkdir(dir, { recursive: true });
  await writeFile(abs, renderQuoteHtml(input), "utf8");
  return { absolutePath: abs, objectKey };
}

export function formatQuoteWhatsappText(input: QuotePdfInput): string {
  const lines = input.lines
    .map(
      (l) =>
        `• ${l.quantity}x ${l.description} — ${money(l.totalCents, input.currency)}`,
    )
    .join("\n");
  return [
    `*${input.tenantName}*`,
    `Quote ${input.quoteNumber}`,
    `Customer: ${input.customerName}`,
    "",
    lines,
    "",
    `*Total: ${money(input.totalCents, input.currency)}*`,
    input.notes ? `\n${input.notes}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}
